apiVersion: v1
kind: ConfigMap
metadata:
  name: observai-backend-config
  namespace: observai-main
data:
  APP_PORT: "8080"
  APP_HOST: "0.0.0.0"
  MONGODB_URL: "mongodb://mongodb-ops-manager:Devdbpass2023@zaga-mongo-ops-manager-db-0.zaga-mongo-ops-manager-db-svc.mongodb-workspace.svc.cluster.local:27017,zaga-mongo-ops-manager-db-1.zaga-mongo-ops-manager-db-svc.mongodb-workspace.svc.cluster.local:27017,zaga-mongo-ops-manager-db-2.zaga-mongo-ops-manager-db-svc.mongodb-workspace.svc.cluster.local:27017/?authMechanism=SCRAM-SHA-256&authSource=admin&connectTimeoutMS=20000&replicaSet=zaga-mongo-ops-manager-db&serverSelectionTimeoutMS=20000"
  TRACE_BOOTSTRAP_URL: "observai-kafka-cluster-kafka-bootstrap.kafka-workspace.svc.cluster.local:9092"
  TRACE_TOPIC: "observai-main-traces-1"
  TRACE_OFFSET_RESET: "latest"
  LOG_BOOTSTRAP_URL: "observai-kafka-cluster-kafka-bootstrap.kafka-workspace.svc.cluster.local:9092"
  LOG_TOPIC: "observai-main-logs-1"
  LOG_OFFSET_RESET: "latest"
  METRIC_BOOTSTRAP_URL: "observai-kafka-cluster-kafka-bootstrap.kafka-workspace.svc.cluster.local:9092"
  METRIC_TOPIC: "observai-main-metrics-1"
  METRIC_OFFSET_RESET: "latest"